### ISSUE TITLE
cert.match is not a function

### ISSUE THREAD

**Issue by bbisesti** [bergie/passport-saml#272] opened 2018-04-04 20:24 UTC
Hello!

I may be doing something incorrect, but I have followed [these steps](https://github.com/bergie/passport-saml/tree/master/docs/adfs) for authenticating my nodeJS application against ADFS and I am getting this error:

cert.match is not a function
TypeError: cert.match is not a function
    at SAML.certToPEM (/Users/bbisesti/GitHub/phishingTrainer/node_modules/passport-saml/lib/passport-saml/saml.js:447:15)
    at Object.getKey (/Users/bbisesti/GitHub/phishingTrainer/node_modules/passport-saml/lib/passport-saml/saml.js:478:19)
    at SignedXml.checkSignature (/Users/bbisesti/GitHub/phishingTrainer/node_modules/xml-crypto/lib/signed-xml.js:256:42)
    at SAML.validateSignature (/Users/bbisesti/GitHub/phishingTrainer/node_modules/passport-saml/lib/passport-saml/saml.js:498:14)
    at /Users/bbisesti/GitHub/phishingTrainer/node_modules/passport-saml/lib/passport-saml/saml.js:545:17
    at _fulfilled (/Users/bbisesti/GitHub/phishingTrainer/node_modules/passport-saml/node_modules/q/q.js:794:54)
    at self.promiseDispatch.done (/Users/bbisesti/GitHub/phishingTrainer/node_modules/passport-saml/node_modules/q/q.js:823:30)
    at Promise.promise.promiseDispatch (/Users/bbisesti/GitHub/phishingTrainer/node_modules/passport-saml/node_modules/q/q.js:756:13)
    at /Users/bbisesti/GitHub/phishingTrainer/node_modules/passport-saml/node_modules/q/q.js:516:49
    at flush (/Users/bbisesti/GitHub/phishingTrainer/node_modules/passport-saml/node_modules/q/q.js:110:17)

Is this something you all are familiar with?

Thank you for your help!

**Comment by markstos** [comment] 2018-04-07 18:47
Please provide code to reproduce the issue, preferably as a failing test for the test suite if you believe you've find a bug.

**Comment by aby040** [comment] 2018-04-17 06:57
@bbisesti what is the value that you have given for the cert attribute? Looks like it is either null or a non-string which throws the '.match is not a function' error! This module expects a string value for the cert option.

**Comment by bbisesti** [comment] 2018-04-17 16:00
Hello @aby040!  I have put this into my .env file: saml_cert=./ssl/server.crt and verified that it exists.  That said I have not debugged the application to see if that is part of my problem.  And to your point @markstos I have not written a test case for this as of yet.  I'm not entirely sure how to go about testing this actually, I am planning on working on that soon however and will let you know how it goes.  I was just hoping that the maintainers of this project may have run into this before and that it was just a configuration problem on my end which someone may have seen before.  Thank you both for your help!

**Comment by hheiskanen** [comment] 2018-05-31 11:49
I just ran into a similar error:
```
TypeError: cert.match is not a function
at SAML.certToPEM (.../node_modules/passport-saml/lib/passport-saml/saml.js:447:15)
```

This can be easily reproduced by passing an array as the `cert` config option. If the project readme is anything to go by, passing arrays (and even functions) as the `cert` option [should be supported](https://github.com/bergie/passport-saml#user-content-security-and-signatures):

> If the Identity Provider has multiple signing certificates that are valid (such as during the rolling from an old key to a new key and responses signed with either key are valid) then the cert configuration key can be an array

However, it doesn't seem to work at all. In my case, the `cert` option was passed an array that contained two strings (incoming and outgoing IdP certs as single-line regular strings).

**Comment by markstos** [comment] 2018-05-31 14:00
@bbisesti Please confirm you are using the latest version of `passport-saml` to make sure the docs you are reading on Github match the code you are actually running.

**Comment by markstos** [comment] 2018-09-27 01:40
I'm closing this due to lack of follow-up from the reports. It appears there may have been an issue with people who were using older versions of `passport-saml`, but reading the documentation for the current version online.

**Closed by markstos** 2018-09-27 01:40 UTC
Labels: need-more-info

**Comment by techtutorials** [comment] 2020-06-08 13:20
> For information, I had this issue because I was using `params.cert = fs.readFileSync(filename)` in the same way I did that for SSL certs used by `https.createServer()`. It works with SSL, but passport-saml does not like the Buffer object returned. I resolved it by getting a string with `fs.readFileSync(filename, 'utf8')`. I hope that helps someone.

Thanks much. Your solution helped me.

**Comment by sgrbhinge** [comment] 2021-08-23 22:24
> For information, I had this issue because I was using `params.cert = fs.readFileSync(filename)` in the same way I did that for SSL certs used by `https.createServer()`. It works with SSL, but passport-saml does not like the Buffer object returned. I resolved it by getting a string with `fs.readFileSync(filename, 'utf8')`. I hope that helps someone.

Thanks brother, it helped.. :)
