### ISSUE TITLE
`body-parser` middleware is required but not documented. 

### ISSUE THREAD

**Issue by clooudch** [bergie/passport-saml#250] opened 2017-11-14 14:21 UTC
I have found out that certain important informations are missing in the documentation. And I think that they possibly should be added to prevent further issues.

I wanted to use this module in a minimal setup. So I decided to not include the body-parser in the middleware pipeline. Unfortunately it turned out that the body-parser is required for this module to work. This dependency is not documented and is in no example included.

I think it would be best if you could add a notice somewhere in the documentation. It would also be okay if the module throws an error when the body-parser middleware is not available.

Please consider adding a notice somewhere or adding this information to the official documentation.

**Comment by markstos** [comment] 2018-01-03 21:57
Closing as dupe of #128. Please search for dupes before opening new tickets.

**Closed by markstos** 2018-01-03 21:57 UTC
Labels: pr-welcome

**Comment by markstos** [comment] 2018-01-03 22:01
@clooudch you are welcome to contribute the refinements requested in PR #151
