### ISSUE TITLE
Nested Signature causes Signature Validation to always fail

### ISSUE THREAD

**Issue by rajivm** [bergie/passport-saml#291] opened 2018-07-20 21:27 UTC
Sensitive data has been removed, but the following SAML response fails due to `validateSignature` detecting "multiple signatures" when using nested signatures. This appears to be due to the xpath being too broad (i.e. pulling out the Signature element that is not just at the same level, but also in the nested levels, i.e. the assertion). 

ORIGINAL XPATH
```
  var xpathSigQuery = ".//*[local-name(.)='Signature' and " +
                      "namespace-uri(.)='http://www.w3.org/2000/09/xmldsig#']";
```

FIXED XPATH
```
  var xpathSigQuery = "./*[local-name(.)='Signature' and " +
                      "namespace-uri(.)='http://www.w3.org/2000/09/xmldsig#']";
```

SOURCE OF VALIDATION FAILURE
```
  // This function is expecting to validate exactly one signature, so if we find more or fewer
  //   than that, reject.
  if (signatures.length != 1) {
		return false;
	}
```

EXAMPLE
```
<samlp:Response
	xmlns:ds="http://www.w3.org/2000/09/xmldsig#"
	xmlns:saml="urn:oasis:names:tc:SAML:2.0:assertion"
	xmlns:samlp="urn:oasis:names:tc:SAML:2.0:protocol"
	xmlns:xs="http://www.w3.org/2001/XMLSchema"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" Destination="https://assertionurl" ID="FIMRSP_b8400a0c-0164-1b6b-8b18-852dfc56c1c1" IssueInstant="2018-07-20T15:12:41Z" Version="2.0">
	<saml:Issuer Format="urn:oasis:names:tc:SAML:2.0:nameid-format:entity">https://idpentity</saml:Issuer>
	<ds:Signature Id="uuidb8400a0d-0164-1c7e-8fb7-852dfc56c1c1">
		<ds:SignedInfo>
			<ds:CanonicalizationMethod Algorithm="http://www.w3.org/2001/10/xml-exc-c14n#"></ds:CanonicalizationMethod>
			<ds:SignatureMethod Algorithm="http://www.w3.org/2001/04/xmldsig-more#rsa-sha256"></ds:SignatureMethod>
			<ds:Reference URI="#FIMRSP_b8400a0c-0164-1b6b-8b18-852dfc56c1c1">
				<ds:Transforms>
					<ds:Transform Algorithm="http://www.w3.org/2000/09/xmldsig#enveloped-signature"></ds:Transform>
					<ds:Transform Algorithm="http://www.w3.org/2001/10/xml-exc-c14n#">
						<xc14n:InclusiveNamespaces
							xmlns:xc14n="http://www.w3.org/2001/10/xml-exc-c14n#" PrefixList="samlp saml xs ds xsi">
						</xc14n:InclusiveNamespaces>
					</ds:Transform>
				</ds:Transforms>
				<ds:DigestMethod Algorithm="http://www.w3.org/2000/09/xmldsig#sha1"></ds:DigestMethod>
				<ds:DigestValue>/xWwTZ859S4dX8bispqySVTNJho=</ds:DigestValue>
			</ds:Reference>
		</ds:SignedInfo>
		<ds:SignatureValue>INTENTIONALLY REMOVED</ds:SignatureValue>
		<ds:KeyInfo>
			<ds:X509Data>
				<ds:X509Certificate>INTENTIONALLY REMOVED</ds:X509Certificate>
			</ds:X509Data>
		</ds:KeyInfo>
	</ds:Signature>
	<samlp:Status>
		<samlp:StatusCode Value="urn:oasis:names:tc:SAML:2.0:status:Success"></samlp:StatusCode>
	</samlp:Status>
	<saml:Assertion ID="Assertion-uuidb84009fd-0164-1f9d-878d-852dfc56c1c1" IssueInstant="2018-07-20T15:12:41Z" Version="2.0">
		<saml:Issuer Format="urn:oasis:names:tc:SAML:2.0:nameid-format:entity">https://issuer</saml:Issuer>
		<ds:Signature Id="uuidb84009fe-0164-1c64-9d98-852dfc56c1c1">
			<ds:SignedInfo>
				<ds:CanonicalizationMethod Algorithm="http://www.w3.org/2001/10/xml-exc-c14n#"></ds:CanonicalizationMethod>
				<ds:SignatureMethod Algorithm="http://www.w3.org/2001/04/xmldsig-more#rsa-sha256"></ds:SignatureMethod>
				<ds:Reference URI="#Assertion-uuidb84009fd-0164-1f9d-878d-852dfc56c1c1">
					<ds:Transforms>
						<ds:Transform Algorithm="http://www.w3.org/2000/09/xmldsig#enveloped-signature"></ds:Transform>
						<ds:Transform Algorithm="http://www.w3.org/2001/10/xml-exc-c14n#">
							<xc14n:InclusiveNamespaces
								xmlns:xc14n="http://www.w3.org/2001/10/xml-exc-c14n#" PrefixList="saml xs xsi">
							</xc14n:InclusiveNamespaces>
						</ds:Transform>
					</ds:Transforms>
					<ds:DigestMethod Algorithm="http://www.w3.org/2000/09/xmldsig#sha1"></ds:DigestMethod>
					<ds:DigestValue>WN+8gAP1KNdieTFIQA9dmW9Vhd8=</ds:DigestValue>
				</ds:Reference>
			</ds:SignedInfo>
			<ds:SignatureValue>INTENTIONALLY REMOVED</ds:SignatureValue>
			<ds:KeyInfo>
				<ds:X509Data>
					<ds:X509Certificate>INTENTIONALLY REMOVED</ds:X509Certificate>
				</ds:X509Data>
			</ds:KeyInfo>
		</ds:Signature>
		<saml:Subject>
			<saml:NameID Format="urn:oasis:names:tc:SAML:1.1:nameid-format:emailAddress">test@example.com</saml:NameID>
			<saml:SubjectConfirmation Method="urn:oasis:names:tc:SAML:2.0:cm:bearer">
				<saml:SubjectConfirmationData NotOnOrAfter="2018-07-20T15:17:41Z" Recipient="https://assertionurl"></saml:SubjectConfirmationData>
			</saml:SubjectConfirmation>
		</saml:Subject>
		<saml:Conditions NotBefore="2018-07-20T15:07:41Z" NotOnOrAfter="2018-07-20T15:17:41Z">
			<saml:AudienceRestriction>
				<saml:Audience>https://audience</saml:Audience>
			</saml:AudienceRestriction>
		</saml:Conditions>
		<saml:AuthnStatement AuthnInstant="2018-07-20T15:12:41Z" SessionIndex="uuidb83ff885-0164-1388-b4f8-852dfc56c1c1" SessionNotOnOrAfter="2018-07-20T16:12:41Z">
			<saml:AuthnContext>
				<saml:AuthnContextClassRef>urn:oasis:names:tc:SAML:2.0:ac:classes:Password</saml:AuthnContextClassRef>
			</saml:AuthnContext>
		</saml:AuthnStatement>
		<saml:AttributeStatement>
			<saml:Attribute Name="mail" NameFormat="urn:oasis:names:tc:SAML:2.0:attrname-format:basic">
				<saml:AttributeValue xsi:type="xs:string">test@example.com</saml:AttributeValue>
			</saml:Attribute>
		</saml:AttributeStatement>
	</saml:Assertion>
</samlp:Response>
```

**Comment by markstos** [comment] 2018-08-03 20:04
This appears to be a dupe of #281 (which may itself by a dupe of even older issues). Closing as a dupe.

**Closed by markstos** 2018-08-03 20:04 UTC
