### ISSUE TITLE
MultiSamlStrategy - UnhandledPromiseRejectionWarning

### ISSUE THREAD

**Issue by tverilytt** [bergie/passport-saml#366] opened 2019-04-04 13:42 UTC
Hi!

I am getting a UnhandledPromiseRejectionWarning in MultiSamlStrategy function, and the function is async, when returning a done with error (or throwing an exception explicitly). Also if trying to return an new Promise reject directly.

Is this a know situation?

Cheers
-jo

(node:4516) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:4516) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by andkrist** [comment] 2019-04-13 20:30
I had this error when I had set validateInResponseTo : true when in an IdP-initiated flow.

**Comment by markstos** [comment] 2019-05-10 00:09
I'm closing this because it sounds like a support request, not a bug report. Note some changes to MultiSaml support were just merged and will appear in the next release.

**Closed by markstos** 2019-05-10 00:09 UTC

**Comment by googamanga** [comment] 2022-08-26 03:51
@tverilytt was this resolved?
